# MQTT Configuration
mqtt:
  broker: "192.168.129.131"
  port: 1883
  user: "spacecomms"
  pass: "i2cati2cat"
  topic_prefix: "devices/os_bru"

# Minio Object Storage
minio:
  endpoint: "192.168.129.131:9000"
  access_key: "minioadmin"
  secret_key: "change_this_to_a_long_password"
  bucket: "images"
  secure: false


# Database Configuration (External PostgreSQL)
database:
  engine: "postgresql"
  host: "172.27.12.100"      # Replace with your PostgreSQL Server IP
  port: 5432
  user: "alessandro_villegas"                 # Replace with your DB user
  pass: "alessandroalessandro"            # Replace with your DB password
  name: "use_cases"              # Replace with your DB name
  path: "telemetry.db"          # Fallback for local testing only


# API Configuration
api:
  telemetry_port: 8001
  image_port: 8002
  host: "0.0.0.0"
